project:
  type: website
  output-dir: docs
  
website:
  title: "Missing data and measurement error"
  repo-url: https://github.com/emmaSkarstein/Missing-data-and-measurement-error
  navbar:
    left:
      - href: index.qmd
        text: " "
  sidebar:
    style: "docked"
    contents:
      - section: "Examples"
        contents:
          - missing_covariate_imputation.qmd
          - missing_and_mismeasured_covariate.qmd
          - simulation_example.qmd
          - simulation_study.qmd
          - example_in_inlabru.qmd
      - section: "Datasets"
        contents:
          - data_bloodpressure.qmd
          - data_nhanes.qmd
          - data_simulated.qmd

format:
  html:
    theme: journal
    toc: true



