project:
  type: website
  output-dir: docs
  
website:
  title: "Missing data and measurement error"
  navbar:
    left:
      - href: index.qmd
        text: " "
  sidebar:
    style: "docked"
    contents:
      - section: "Datasets"
        contents:
          - data_bloodpressure.qmd
          - data_nhanes.qmd
          - data_simulated.qmd
      - section: "Examples from the paper"
        contents:
          - missing_covariate_imputation.qmd
          - missing_and_mismeasured_covariate.qmd
          - simulation_study.qmd
      - section: "Additional examples"
        contents: 
          - simulation_example.qmd
          - example_in_inlabru.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true



